import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import { StudentAvailabilityForm } from "~/components/studentAvailability/StudentAvailabilityForm";
import { StudentAvailabilityTable } from "~/components/studentAvailability/StudentAvailabilityTable";
import { TutorAvailabilityForm } from "~/components/tutorAvailability/TutorAvailabilityForm";
import { TutorAvailabilityTable } from "~/components/tutorAvailability/TutorAvailabilityTable";

const Home: NextPage = () => {
  const user = useUser();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col">
        <nav className="flex w-full justify-center p-4">
          <div>
            {!user.isSignedIn && (
              <div className="rounded bg-purple-600 p-4 text-white">
                <SignInButton />
              </div>
            )}
          </div>
          <div>
            {!!user.isSignedIn && (
              <div className="rounded bg-purple-600 p-4 text-white">
                <SignOutButton />
              </div>
            )}
          </div>
        </nav>
        <TutorAvailabilityForm />
        <TutorAvailabilityTable />
        <StudentAvailabilityForm />
        <StudentAvailabilityTable />
      </main>
    </>
  );
};

export default Home;
